var annotated_dup =
[
    [ "ifm3d", null, [
      [ "calibration", null, [
        [ "Calibration", "structifm3d_1_1calibration_1_1Calibration.html", "structifm3d_1_1calibration_1_1Calibration" ],
        [ "ExtrinsicOpticToUser", "structifm3d_1_1calibration_1_1ExtrinsicOpticToUser.html", "structifm3d_1_1calibration_1_1ExtrinsicOpticToUser" ]
      ] ],
      [ "ArrayDeserialize", "classifm3d_1_1ArrayDeserialize.html", "classifm3d_1_1ArrayDeserialize" ],
      [ "Buffer", "classifm3d_1_1Buffer.html", "classifm3d_1_1Buffer" ],
      [ "Buffer_", "classifm3d_1_1Buffer__.html", "classifm3d_1_1Buffer__" ],
      [ "Device", "classifm3d_1_1Device.html", "classifm3d_1_1Device" ],
      [ "DistanceImageInfo", "classifm3d_1_1DistanceImageInfo.html", "classifm3d_1_1DistanceImageInfo" ],
      [ "Error", "classifm3d_1_1Error.html", "classifm3d_1_1Error" ],
      [ "Frame", "classifm3d_1_1Frame.html", "classifm3d_1_1Frame" ],
      [ "FrameGrabber", "classifm3d_1_1FrameGrabber.html", "classifm3d_1_1FrameGrabber" ],
      [ "IFMNetworkDevice", "classifm3d_1_1IFMNetworkDevice.html", "classifm3d_1_1IFMNetworkDevice" ],
      [ "IntrinsicCalibration", "structifm3d_1_1IntrinsicCalibration.html", "structifm3d_1_1IntrinsicCalibration" ],
      [ "IteratorAdapter", "classifm3d_1_1IteratorAdapter.html", "classifm3d_1_1IteratorAdapter" ],
      [ "json", "classifm3d_1_1json.html", null ],
      [ "LegacyDevice", "classifm3d_1_1LegacyDevice.html", "classifm3d_1_1LegacyDevice" ],
      [ "LogEntry", "classifm3d_1_1LogEntry.html", "classifm3d_1_1LogEntry" ],
      [ "LogFormatterJson", "classifm3d_1_1LogFormatterJson.html", null ],
      [ "LogFormatterText", "classifm3d_1_1LogFormatterText.html", null ],
      [ "Logger", "classifm3d_1_1Logger.html", "classifm3d_1_1Logger" ],
      [ "LogWriter", "classifm3d_1_1LogWriter.html", "classifm3d_1_1LogWriter" ],
      [ "LogWriterComposite", "classifm3d_1_1LogWriterComposite.html", "classifm3d_1_1LogWriterComposite" ],
      [ "LogWriterConsole", "classifm3d_1_1LogWriterConsole.html", "classifm3d_1_1LogWriterConsole" ],
      [ "LogWriterConsoleColored", "classifm3d_1_1LogWriterConsoleColored.html", "classifm3d_1_1LogWriterConsoleColored" ],
      [ "LogWriterFile", "classifm3d_1_1LogWriterFile.html", "classifm3d_1_1LogWriterFile" ],
      [ "O3D", "classifm3d_1_1O3D.html", "classifm3d_1_1O3D" ],
      [ "O3R", "classifm3d_1_1O3R.html", "classifm3d_1_1O3R" ],
      [ "O3RSealedBox", "classifm3d_1_1O3RSealedBox.html", "classifm3d_1_1O3RSealedBox" ],
      [ "O3X", "classifm3d_1_1O3X.html", "classifm3d_1_1O3X" ],
      [ "ODSExtrinsicCalibrationCorrectionV1", "classifm3d_1_1ODSExtrinsicCalibrationCorrectionV1.html", "classifm3d_1_1ODSExtrinsicCalibrationCorrectionV1" ],
      [ "ODSInfoV1", "classifm3d_1_1ODSInfoV1.html", "classifm3d_1_1ODSInfoV1" ],
      [ "ODSOccupancyGridV1", "classifm3d_1_1ODSOccupancyGridV1.html", "classifm3d_1_1ODSOccupancyGridV1" ],
      [ "ODSPolarOccupancyGridV1", "classifm3d_1_1ODSPolarOccupancyGridV1.html", "classifm3d_1_1ODSPolarOccupancyGridV1" ],
      [ "Organizer", "classifm3d_1_1Organizer.html", "classifm3d_1_1Organizer" ],
      [ "PCICClient", "classifm3d_1_1PCICClient.html", "classifm3d_1_1PCICClient" ],
      [ "Point", "structifm3d_1_1Point.html", "structifm3d_1_1Point" ],
      [ "PortInfo", "structifm3d_1_1PortInfo.html", "structifm3d_1_1PortInfo" ],
      [ "RGBInfoV1", "classifm3d_1_1RGBInfoV1.html", "classifm3d_1_1RGBInfoV1" ],
      [ "SemVer", "structifm3d_1_1SemVer.html", "structifm3d_1_1SemVer" ],
      [ "SWUpdater", "classifm3d_1_1SWUpdater.html", "classifm3d_1_1SWUpdater" ],
      [ "TOFInfoV3", "classifm3d_1_1TOFInfoV3.html", "classifm3d_1_1TOFInfoV3" ],
      [ "TOFInfoV4", "classifm3d_1_1TOFInfoV4.html", "classifm3d_1_1TOFInfoV4" ]
    ] ],
    [ "O3DExposureTimes", "classifm3d_1_1O3DExposureTimes.html", null ],
    [ "O3DExtrinsicCalibration", "classifm3d_1_1O3DExtrinsicCalibration.html", null ],
    [ "O3DILLUTemperature", "classifm3d_1_1O3DILLUTemperature.html", null ],
    [ "O3DInstrinsicCalibration", "classifm3d_1_1O3DInstrinsicCalibration.html", null ],
    [ "O3DInverseInstrinsicCalibration", "classifm3d_1_1O3DInverseInstrinsicCalibration.html", null ]
];